Added failure catch

diff --git a/ddns-cloudflare/rootfs/usr/bin/ddns-cloudflare-update b/ddns-cloudflare/rootfs/usr/bin/ddns-cloudflare-update
--- a/ddns-cloudflare/rootfs/usr/bin/ddns-cloudflare-update
+++ b/ddns-cloudflare/rootfs/usr/bin/ddns-cloudflare-update
@@ -19,9 +19,15 @@ ZONE_ID=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=${HOST
     -H "Content-Type: application/json" \
     -H "X-Auth-Email: ${CLOUDFLARE_EMAIL}" \
     -H "Authorization: Bearer ${CLOUDFLARE_SECRET}" \
-    | jq -r '{"result"}[] | .[0] | .id')
+    | jq -r '{result"}[] | .[0] | .id')
 
 echo "Cloudflare DNS Zone ID has been fetched: ${ZONE_ID}"
+
+if ["${ZONE_ID}" = '']
+then
+    echo "Failed to aquire Cloudflare DNS Zone ID"
+    exit 1
+fi
 
 DNS_RECORD_ID=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records?type=${RECORD_TYPE}&name=${DATA_VALUE}" \
     -H "Accept: application/json" \
@@ -30,7 +36,13 @@ DNS_RECORD_ID=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${ZON
     -H "Authorization: Bearer ${CLOUDFLARE_SECRET}" \
     | jq -r '{"result"}[] | .[0] | .id')
 
-echo "Cloudflare DNS Record ID for ${HOSTNAME} has been fetched: ${DNS_RECORD_ID}" \
+echo "Cloudflare DNS Record ID for ${HOSTNAME} has been fetched: ${DNS_RECORD_ID}"
+
+if ["${DNS_RECORD_ID}" = '']
+then
+    echo "Failed to aquire Cloudflare DNS Record ID"
+    exit 1
+fi
 
 if [ "${ACTION}" = 'remove' ]
 then
